theme = "hugo-theme-techdoc"

title = "DataStax Workshop"

googleAnalytics = "UA-120591772-2"

# For search functionality
[outputs]
home = [ "HTML"]

[params]

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
weight = 1
languageName = "English"

[Languages.fr]
weight = 2
languageName = "Français"

[Languages.pt]
weight = 2
languageName = "Português"

[Languages.es]
weight = 2
languageName = "Español"

[markup.goldmark.renderer]
 unsafe = true

